In [3]:
import pandas as pd

In [17]:
df= pd.read_csv(r"C:\Users\Hey!\OneDrive\Desktop\Pandas-for-Data-Science\dataset\countries of the world.csv")
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [19]:
df.head()   # first 5 rows

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [22]:
df.head(10)   # first 10 rows

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES

In [23]:
df.tail()   # last 5 rows

                Country                               Region
217            Vanuatu   OCEANIA
218          Venezuela               LATIN AMER. & CARIB
219            Vietnam         ASIA (EX. NEAR EAST)
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
222          West Bank   NEAR EAST
223     Western Sahara   NORTHERN AFRICA
224              Yemen   NEAR EAST
225             Zambia   SUB-SAHARAN AFRICA
226           Zimbabwe   SUB-SAHARAN AFRICA

In [41]:
df.tail(10)   # last 10 rows

                Country                               Region
217            Vanuatu   OCEANIA
218          Venezuela               LATIN AMER. & CARIB
219            Vietnam         ASIA (EX. NEAR EAST)
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
222          West Bank   NEAR EAST
223     Western Sahara   NORTHERN AFRICA
224              Yemen   NEAR EAST
225             Zambia   SUB-SAHARAN AFRICA
226           Zimbabwe   SUB-SAHARAN AFRICA

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  227 non-null    str
 1   Region   227 non-null    str
dtypes: str(2)
memory usage: 3.7 KB

In [25]:
df.describe()

             Country                               Region
count            227                                  227
unique           227                                   11
top     Afghanistan   SUB-SAHARAN AFRICA
freq               1                                   51

In [27]:
df.shape    # rows x columns

(227, 2)

In [28]:
df.dtypes

Country    str
Region     str
dtype: object

In [33]:
df["Region"].value_counts()

Region
SUB-SAHARAN AFRICA                     51
LATIN AMER. & CARIB                    45
ASIA (EX. NEAR EAST)                   28
WESTERN EUROPE                         28
OCEANIA                                21
NEAR EAST                              16
EASTERN EUROPE                         12
C.W. OF IND. STATES                    12
NORTHERN AFRICA                         6
NORTHERN AMERICA                        5
BALTICS                                 3
Name: count, dtype: int64

In [36]:
df.isnull().sum()

Country    0
Region     0
dtype: int64

In [37]:
df.nunique()

Country    227
Region      11
dtype: int64

In [39]:
df.sample(20)   # random samples

                               Country                               Region
175  Saint Vincent and the Grenadines               LATIN AMER. & CARIB
86                             Guinea   SUB-SAHARAN AFRICA
29                             Brunei         ASIA (EX. NEAR EAST)
95                          Indonesia         ASIA (EX. NEAR EAST)
19                            Belgium   WESTERN EUROPE
13                         Azerbaijan                  C.W. OF IND. STATES
129                             Malta   WESTERN EUROPE
188                           Somalia   SUB-SAHARAN AFRICA
197                             Syria   NEAR EAST
142                        Mozambique   SUB-SAHARAN AFRICA
90                           Honduras               LATIN AMER. & CARIB
204                 Trinidad & Tobago               LATIN AMER. & CARIB
198                            Taiwan         ASIA (EX. NEAR EAST)
97                               Iraq   NEAR EAST
154                            Norway   WESTERN EUROPE
37                         Cape Verde   SUB-SAHARAN AFRICA
73                        Gambia, The   SUB-SAHARAN AFRICA
64                            Estonia   BALTICS
39               Central African Rep.   SUB-SAHARAN AFRICA
114                            Latvia   BALTICS

In [40]:
df.memory_usage()

Index       132
Country    1816
Region     1816
dtype: int64