In [24]:
import pandas as pd

In [25]:
data = {
    "Name": ["Bruce", "Harvy", "joker", "bane", "cordern"],
    "Age": [21, 25, 23, 28, 26],
    "Salary": [30000, 50000, 45000, 60000, 52000]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary
0    Bruce   21   30000
1    Harvy   25   50000
2    joker   23   45000
3     bane   28   60000
4  cordern   26   52000

## df.sort_values()

In [26]:
# Sort by single column
df.sort_values(by="Salary")  # defualt order 'ascending'

      Name  Age  Salary
0    Bruce   21   30000
2    joker   23   45000
1    Harvy   25   50000
4  cordern   26   52000
3     bane   28   60000

In [27]:
# Sort descending
df.sort_values(by="Salary", ascending=False)

      Name  Age  Salary
3     bane   28   60000
4  cordern   26   52000
1    Harvy   25   50000
2    joker   23   45000
0    Bruce   21   30000

In [35]:
# Sort by multiple columns
df.sort_values(by=["Age", "Salary"])

      Name  Age  Salary
0    Bruce   21   30000
2    joker   23   45000
1    Harvy   25   50000
4  cordern   26   52000
3     bane   28   60000

## df.sort_index()

In [36]:
# Shuffle index first
df_shuffled = df.sample(frac=1)

In [37]:
# Sort by index
df_shuffled.sort_index()

      Name  Age  Salary
0    Bruce   21   30000
1    Harvy   25   50000
2    joker   23   45000
3     bane   28   60000
4  cordern   26   52000

## df.rank()

In [38]:
# Rank salaries
df["Salary"].rank()

0    1.0
1    3.0
2    2.0
3    5.0
4    4.0
Name: Salary, dtype: float64

In [39]:
# Rank with highest as rank 1
df["Salary"].rank(ascending=False)

0    5.0
1    3.0
2    4.0
3    1.0
4    2.0
Name: Salary, dtype: float64

## df.nlargest()

In [40]:
# Top 3 highest salaries
df.nlargest(3, "Salary")

      Name  Age  Salary
3     bane   28   60000
4  cordern   26   52000
1    Harvy   25   50000

## df.nsmallest()

In [41]:
# Bottom 2 lowest salaries
df.nsmallest(2, "Salary")

    Name  Age  Salary
0  Bruce   21   30000
2  joker   23   45000