In [15]:
import pandas as pd
import numpy as np

data = {
    "A": [10, 20, 30, 40, 50],
    "B": [5, 15, 25, 35, 45],
    "C": [2, 4, 6, 8, 10]
}

df = pd.DataFrame(data)
df

    A   B   C
0  10   5   2
1  20  15   4
2  30  25   6
3  40  35   8
4  50  45  10

## df.mean()

In [16]:
df.mean()

A    30.0
B    25.0
C     6.0
dtype: float64

## df.sum()

In [17]:
df.sum()

A    150
B    125
C     30
dtype: int64

## df.median()

In [18]:
df.median()

A    30.0
B    25.0
C     6.0
dtype: float64

## df.std() / df.var()

In [19]:
df.std()
df.var()

A    250.0
B    250.0
C     10.0
dtype: float64

## df.corr()

In [20]:
df.corr()

     A    B    C
A  1.0  1.0  1.0
B  1.0  1.0  1.0
C  1.0  1.0  1.0

## df.cumsum()

In [21]:
df.cumsum()

     A    B   C
0   10    5   2
1   30   20   6
2   60   45  12
3  100   80  20
4  150  125  30

## df.pct_change()

In [23]:
df.pct_change()

          A         B         C
0       NaN       NaN       NaN
1  1.000000  2.000000  1.000000
2  0.500000  0.666667  0.500000
3  0.333333  0.400000  0.333333
4  0.250000  0.285714  0.250000

## df.cov()

In [24]:
df.cov()

       A      B     C
A  250.0  250.0  50.0
B  250.0  250.0  50.0
C   50.0   50.0  10.0

## df.quantile()

In [25]:
df.quantile(0.5)  # median

A    30.0
B    25.0
C     6.0
Name: 0.5, dtype: float64

## df.abs()

In [26]:
df_negative = pd.DataFrame({"A": [-10, -20, 30]})

df_negative.abs()

    A
0  10
1  20
2  30

## df.diff()

In [27]:
df.diff()

      A     B    C
0   NaN   NaN  NaN
1  10.0  10.0  2.0
2  10.0  10.0  2.0
3  10.0  10.0  2.0
4  10.0  10.0  2.0