In [1]:
import pandas as pd

data = {
    "Name": ["Logesh", "John", "Alice", "Bob", "Charlie"],
    "Gender": ["Male", "Male", "Female", "Male", "Female"],
    "Marks": [45, 67, 89, 55, 72]
}

df = pd.DataFrame(data)
df

      Name  Gender  Marks
0   Logesh    Male     45
1     John    Male     67
2    Alice  Female     89
3      Bob    Male     55
4  Charlie  Female     72

## pd.Categorical()

In [2]:
df["Gender"] = pd.Categorical(df["Gender"], categories=["Male", "Female"])
df.dtypes

Name           str
Gender    category
Marks        int64
dtype: object

## pd.get_dummies()

In [3]:
pd.get_dummies(df["Gender"], drop_first=True)

   Female
0   False
1   False
2    True
3   False
4    True

## pd.cut()

In [4]:
bins = [0, 50, 70, 100]
labels = ["Low", "Medium", "High"]

df["Marks_Category"] = pd.cut(df["Marks"], bins=bins, labels=labels)
df

      Name  Gender  Marks Marks_Category
0   Logesh    Male     45            Low
1     John    Male     67         Medium
2    Alice  Female     89           High
3      Bob    Male     55         Medium
4  Charlie  Female     72           High

## pd.qcut()

In [5]:
df["Marks_Quantile"] = pd.qcut(df["Marks"], q=3)
df

      Name  Gender  Marks Marks_Category  Marks_Quantile
0   Logesh    Male     45            Low  (44.999, 59.0]
1     John    Male     67         Medium  (59.0, 70.333]
2    Alice  Female     89           High  (70.333, 89.0]
3      Bob    Male     55         Medium  (44.999, 59.0]
4  Charlie  Female     72           High  (70.333, 89.0]

## df.cat.*

In [12]:
# Category codes
print(df["Gender"].cat.codes)

# Categories
print(df["Gender"].cat.categories)

# Add new category
df["Gender"] = df["Gender"].cat.add_categories(['other'])
print(df["Gender"].cat.categories)

0    0
1    0
2    1
3    0
4    1
dtype: int8
Index(['Male', 'Female', 'Other'], dtype='str')
Index(['Male', 'Female', 'Other', 'other'], dtype='str')